### ISSUE TITLE
Please consider upgrading dependencies to Dart3/Flutter 3.1, e.g. http->1.0.0

### ISSUE THREAD

**Issue by MagnusJohansson** [rinukkusu/spotify-dart#167]
When trying to use the latest [http v1.0.0 package](https://pub.dev/packages/http), I get this dep. error:
```
Because spotify 0.11.0 depends on http ^0.13.3 and no versions of spotify match >0.11.0 <0.12.0, spotify ^0.11.0 requires http ^0.13.3.
So, because my_app depends on both http ^1.0.0 and spotify ^0.11.0, version solving failed.
```

Please consider using the latest [http package](https://pub.dev/packages/http).
Thanks.

**Comment by hayribakici** [comment]
@MagnusJohansson As a workaround, you could try to [override](https://dart.dev/tools/pub/dependencies#dependency-overrides) the `http` dependency: 

```yml
name: my_app
dependencies:
  spotify: ^0.11.0
dependency_overrides:
  http: '1.0.0`
```
